name: ".NET build and test"

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
          8.0.x
          9.0.x
          10.0.x
    - name: Restore dependencies
      run: dotnet restore src/KetupaPredicates.slnx
    - name: Build
      run: dotnet build src/KetupaPredicates.slnx --no-restore
    - name: Test
      run: dotnet test src/KetupaPredicates.slnx --no-build --verbosity normal
